### PR TITLE
added lenght cuz length is already implemented

### PR DESCRIPTION
**Pull request by koreaneggroll**

### CODE REVIEW

**Comment by midnqp** [comment]
Quite depressingly, `len()` doesn't yet support multiple data types. We need to finish up `__test__.c` so that we know what works and what doesn't. And, I'm currently thinking about introducing `list() dict()` into the project and researching accordingly. 

But that may be an overkill. So, I better think about it later.

**Comment by koreaneggroll** [comment]
wdym multiple datatypes, it's supposed to tell the length of an array, even in python, it doesn't say the length of an integer. Only if you want to add so it tells you the length of a string, which is pretty easy

**Comment by midnqp** [comment]
You're right, just array & strings for `len()`.

Can you do: `len(array)   len(string)`? Under that same function name? It'll just be a loop in a macro `len()`.

**Comment by koreaneggroll** [comment]
Yeah, gonna get on it

**Comment by koreaneggroll** [comment]
For some weird reason it doesn't get the correct length of an array in the function which is weird.

**Comment by koreaneggroll** [comment]
I'll start working on smth else and if I get an idea on how to fix it I will be right on it

**Comment by midnqp** [comment]
> For some weird reason it doesn't get the correct length of an array in the function which is weird.

Great job you discovered that, **adventurer!** I knew this. I faced this before, and that was a reason why it was not marked implemented. I talked about this on my post on reddit with a person.

@koreaneggroll , let's just think about this later - because it seems critical right now.

**Comment by koreaneggroll** [comment]
understood

**Comment by midnqp** [comment]
`list_len()` is implemented

**Pull request closed without merging**
